spring:
    application:
        name: serie-service
    config:
        import: optional:configserver:http://localhost:8888

        rabbitmq:
            username: guest
            password: guest
            host: localhost
            port: 5672
            zipkin:
                base-url: http://localhost:9411/
                enabled: true

        queue:
            persona:
                name: SerieQueue

        message: registro now up
